openapi: 3.0.3
info:
  title: Excise Movement Control System API
  description: |-
    Use the EMCS API to submit excise movement notifications to the Excise Movement and Control System (EMCS). You can also send and receive messages about excise movements and retrieve information about excise traders. 
    
    The [EMCS API service guide](/guides/emcs-api-service-guide/) contains a detailed overview of v1.0 of the API.

    Testing instructions can be found in the [EMCS API testing guide](/guides/emcs-api-testing-guide/).
  contact: { }
  version: "1.0.0"
servers:
  - url: https://test-api.service.hmrc.gov.uk
    description: Sandbox
  - url: https://api.service.hmrc.gov.uk
    description: Production
tags:
  - name: Movements
    description: Create, amend or cancel an excise movement
  - name: Traders
    description: Information relating to excise traders
paths:
  /customs/excise/movements:
    post:
      tags:
        - Movements
      summary: Submit a new draft excise movement
      description: Submit a new draft excise movement. </br></br>**Note:** The consignor ID in the IE815 message must match an excise reference number (ERN) in the bearer token that you use for API authentication. If it does not, a 403 Forbidden error will be thrown.
      operationId: submitMovement
      parameters:
        - $ref: "#/components/parameters/AcceptHeader"
        - $ref: "#/components/parameters/ContentTypeHeader"
      requestBody:
        description: |
          The body for this request should be an XML body that conforms to the [IE815 XML Schema](https://github.com/hmrc/excise-movement-control-system-api/blob/main/app/xsd/ie815.xsd)
          
          An example can be found [here](https://github.com/hmrc/excise-movement-control-system-api/blob/main/resources/public/api/conf/1.0/examples/IE815.xml)

        required: true
        content:
          application/xml:
            schema:
              $ref: '#/components/schemas/IE815'
            examples:
              submitDraftMovement:
                summary: Submit draft movement (IE815)
                value: '<IE815><!-- Example IE815 message --></IE815>'
      responses:
        '202':
          description: Accepted
          content:
            application/vnd.hmrc.1.0+json:
              schema:
                $ref: '#/components/schemas/ExciseMovement'
              example:
                consignorId: "GBWK002281023"
                consigneeId: "GBWKQOZ8OVLYR"
                localReferenceNumber: "LRNQA20230909022221"
                status: "Accepted"
        '400':
          description: The submission of draft movement message has failed validation
          content:
            application/vnd.hmrc.1.0+json:
              schema:
                $ref: '#/components/schemas/ExciseMovementError'
              examples:
                jsonValidation:
                  summary: "Json validation error downstream"
                  value:
                    dateTime: "2021-12-17T09:30:47Z"
                    message: "Json validation failed"
                    debugMessage: "user is missing but it is required"
                    emcsCorrelationId: "3e8dae97-b586-4cef-8511-68ac12da9028"
                xmlValidation:
                  summary: "Xml validation failure"
                  value:
                    message: "Validation error(s) occurred"
                    errors:
                      - errorCode: 8084
                        errorMessage: "The Date of Dispatch you entered is incorrect. It must be today or later. Please amend your entry and resubmit."
                        location: "/urn:IE815[1]/urn:Body[1]/urn:SubmittedDraftOfEADESAD[1]/urn:EadEsadDraft[1]/urn:DateOfDispatch[1]"
                        value: "2023-09-09"
        '401':
          description: Consignor not authorized. Invalid enrolment parameter.
        '403':
          description: Consignor ID is not in authorisation bearer token
        '404':
          description: Connection Refused
          content:
            application/vnd.hmrc.1.0+json:
              schema:
                $ref: '#/components/schemas/ExciseMovementError'
              example:
                dateTime: "2021-12-17T09:30:47Z"
                message: "Received error response from server"
                debugMessage: "Connection refused; nested exception is java.net.ConnectException: Connection refused"
                emcsCorrelationId: "3e8dae97-b586-4cef-8511-68ac12da9028"
        '500':
          description: Internal server error
          content:
            application/vnd.hmrc.1.0+json:
              schema:
                $ref: '#/components/schemas/ExciseMovementError'
              example:
                dateTime: "2021-12-17T09:30:47Z"
                message: "Invalid JSON structure"
                debugMessage: "JSON parse error: Unexpected character"
                emcsCorrelationId: "3e8dae97-b586-4cef-8511-68ac12da9028"
        '503':
          description: Downstream service is Unavailable
          content:
            application/vnd.hmrc.1.0+json:
              schema:
                $ref: '#/components/schemas/ExciseMovementError'
              example:
                code: "SERVER_ERROR"
                message: "Service unavailable"
      security:
        - userRestricted:
            - excise-movement-control-system
    get:
      tags:
        - Movements
      summary: Get excise movements
      description: Get excise movements. </br></br>**Note:** You will only be able to retrieve movements where the consignor ID or consignee ID of the movement matches any of your excise reference numbers (ERNs) in the bearer token that you use for API authentication.
      operationId: getAllMovements
      parameters:
        - $ref: "#/components/parameters/AcceptHeader"
        - name: ern
          in: query
          description: Filter excise movements by excise reference number (consignor ID/consignee ID). If you do not provide an excise reference number (ERN) as a query parameter, you will get a list for all ERNs in your bearer token.
          required: false
          schema:
            type: string
        - name: arc
          in: query
          description: Filter excise movements by administrative reference code (ARC). This will return one movement in the list.
          required: false
          schema:
            type: string
        - name: lrn
          in: query
          description: Filter excise movements by local reference number (LRN)
          required: false
          schema:
            type: string
        - name: updatedSince
          in: query
          description: Filter excise movements modified after provided timestamp.<br/>This can be used to poll for any updated movements.<br/>For each updated movement that gets returned, you can then call the get messages endpoint and pass in the same value for its "updatedSince" query parameter to get the messages that have been received since you last polled.
          required: false
          schema:
            $ref: "#/components/schemas/DateTime"
      responses:
        '200':
          description: Successful operation. If there are no movements for any of your excise reference numbers (ERNs) in your bearer token or because of the filters, this will return an empty list.
          content:
            application/vnd.hmrc.1.0+json:
              example:
                - consignorId: "GBWK002281023"
                  consigneeId: "GBWKQOZ8OVLYR"
                  localReferenceNumber: "LRNQA20230909022221"
                  administrativeReferenceCode: "35WE3B5EDSYSZ86STVKH8"
                  status: "Accepted"
                - consignorId: "GBWK002281023"
                  consigneeId: "GBWKQOZ8OVLYQ"
                  localReferenceNumber: "LRNQA20230909022224"
                  status: "None"
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ExciseMovement'
        '401':
          description: Consignor or Consignee not authorized. Invalid enrolment parameter.
      security:
        - userRestricted:
            - excise-movement-control-system
  /customs/excise/movements/{localReferenceNumber}/messages:
    post:
      tags:
        - Movements
      summary: Submit a message for an excise movement.
      description: |
        Submit a message for a specific excise movement. </br></br>
        The **X-Message-Type** header **must** be the same as the message body e.g. for an **IE818 (Record of receipt) message** the **X-Message-Type** header also needs to be **IE818**
        
        **Note:** The consignor ID or consignee ID in the message must match an excise reference number (ERN) in the bearer token that you use for API authentication. If it does not, a 403 Forbidden error will be thrown.
      operationId: postMessage
      parameters:
        - $ref: '#/components/parameters/AcceptHeader'
        - $ref: '#/components/parameters/ContentTypeHeader'
        - name: localReferenceNumber
          in: path
          description: The excise movement identifier
          required: true
          schema:
            type: string
        - name: X-Message-Type
          in: header
          description: The message type
          required: true
          schema:
            $ref: '#/components/schemas/IncomingMessageType'
      requestBody:
        required: true
        content:
          application/xml:
            schema:
              # I tried to use a "oneOf" here but the examples didn't work so using a GenericXML object instead.
              type: object
              xml:
                name: GenericXML
            examples:
              cancellation:
                summary: Submit cancellation (IE810)
                description: |
                  The body for this request should be an XML body that conforms to the [IE810 XML Schema](https://github.com/hmrc/excise-movement-control-system-api/blob/main/app/xsd/ie810.xsd)
                  
                  An example can be found [here](https://github.com/hmrc/excise-movement-control-system-api/blob/main/resources/public/api/conf/1.0/examples/IE810.xml)
                value: '<IE810><!-- Example IE810 message --></IE810>'
              changeOfDestination:
                summary: Submit change of destination (IE813)
                description: |
                  The body for this request should be an XML body that conforms to the [IE813 XML Schema](https://github.com/hmrc/excise-movement-control-system-api/blob/main/app/xsd/ie813.xsd)
                  
                  An example can be found [here](https://github.com/hmrc/excise-movement-control-system-api/blob/main/resources/public/api/conf/1.0/examples/IE813.xml)
                value: '<IE813><!-- Example IE813 message --></IE813>'
              reportOfReceipt:
                summary: Submit report of receipt (IE818)
                description: |
                  The body for this request should be an XML body that conforms to the [IE818 XML Schema](https://github.com/hmrc/excise-movement-control-system-api/blob/main/app/xsd/ie818.xsd)
                  
                  An example can be found [here](https://github.com/hmrc/excise-movement-control-system-api/blob/main/resources/public/api/conf/1.0/examples/IE818.xml)
                value: '<IE818><!-- Example IE818 message --></IE818>'
              alertOrRejection:
                summary: Submit alert or rejection (IE819)
                description: |
                  The body for this request should be an XML body that conforms to the [IE819 XML Schema](https://github.com/hmrc/excise-movement-control-system-api/blob/main/app/xsd/ie819.xsd)
                  
                  An example can be found [here](https://github.com/hmrc/excise-movement-control-system-api/blob/main/resources/public/api/conf/1.0/examples/IE819.xml)
                value: '<IE819><!-- Example IE819 message --></IE819>'
              #              Temporarily commented out until MVP+
              #              split:
              #                summary: Submit split movement (IE825)
              #                description: The body for this request should be an XML body that conforms to the [IE825 XML Schema](https://github.com/hmrc/excise-movement-control-system-api/blob/main/app/xsd/ie825.xsd)
              #                value: '<IE825><!-- Example IE825 message --></IE825>'
              explainDelayToDelivery:
                summary: Submit explain delay to delivery (IE837)
                description: |
                  The body for this request should be an XML body that conforms to the [IE837 XML Schema](https://github.com/hmrc/excise-movement-control-system-api/blob/main/app/xsd/ie837.xsd)
                  
                  An example submitted by the consignor can be found [here](https://github.com/hmrc/excise-movement-control-system-api/blob/main/resources/public/api/conf/1.0/examples/IE837_consignor.xml)
                  
                  An example submitted by the consignee can be found [here](https://github.com/hmrc/excise-movement-control-system-api/blob/main/resources/public/api/conf/1.0/examples/IE837_consignee.xml)
                value: '<IE837><!-- Example IE837 message --></IE837>'
              reasonForShortage:
                summary: Submit reason for shortage (IE871)
                description: |
                  The body for this request should be an XML body that conforms to the [IE871 XML Schema](https://github.com/hmrc/excise-movement-control-system-api/blob/main/app/xsd/ie871.xsd)
                  
                  An example can be found [here](https://github.com/hmrc/excise-movement-control-system-api/blob/main/resources/public/api/conf/1.0/examples/IE871.xml)
                value: '<IE871><!-- Example IE871 message --></IE871>'
      responses:
        '202':
          description: Message accepted
        '400':
          description: The submitted message has failed validation
          content:
            application/vnd.hmrc.1.0+json:
              schema:
                $ref: '#/components/schemas/ExciseMovementError'
              example:
                dateTime: "2021-12-17T09:30:47Z"
                message: "Json validation failed"
                debugMessage: "user is missing but it is required"
                emcsCorrelationId: "3e8dae97-b586-4cef-8511-68ac12da9028"
        '401':
          description: Consignor or Consignee not authorized. Invalid enrolment parameter.
        '403':
          description: Consignor ID or consignee ID in submitted message is not in authorisation bearer token
        '404':
          description: Unknown excise movement identifier
          content:
            application/vnd.hmrc.1.0+json:
              schema:
                $ref: '#/components/schemas/ExciseMovementError'
              example:
                dateTime: "2021-12-17T09:30:47Z"
                message: "Received error response from server"
                debugMessage: "Connection refused; nested exception is java.net.ConnectException: Connection refused"
                emcsCorrelationId: "3e8dae97-b586-4cef-8511-68ac12da9028"
        '500':
          description: Internal server error
          content:
            application/vnd.hmrc.1.0+json:
              schema:
                $ref: '#/components/schemas/ExciseMovementError'
              example:
                dateTime: "2021-12-17T09:30:47Z"
                message: "Invalid JSON structure"
                debugMessage: "JSON parse error: Unexpected character"
                emcsCorrelationId: "3e8dae97-b586-4cef-8511-68ac12da9028"
        '503':
          description: Downstream service is Unavailable
          content:
            application/vnd.hmrc.1.0+json:
              schema:
                $ref: '#/components/schemas/ExciseMovementError'
              example:
                code: "SERVER_ERROR"
                message: "Service unavailable"
      security:
        - userRestricted:
            - excise-movement-control-system
    get:
      tags:
        - Movements
      summary: Get all messages for an excise movement using the localReferenceNumber
      description: Get all messages for a specific excise movement. </br></br>**Note:** The consignor ID or consignee ID must match an excise reference number (ERN) in the bearer token that you use for API authentication. If it does not, a 403 Forbidden error will be thrown.
      operationId: getAllMessages
      parameters:
        - $ref: "#/components/parameters/AcceptHeader"
        - name: localReferenceNumber
          in: path
          description: The local reference number of the movement
          required: true
          schema:
            type: string
        - name: updatedSince
          in: query
          description: Filter messages received after provided timestamp.<br/>This can be used to poll for new messages per ERN/LRN combination.<br/>You can also poll on the get movements endpoint which allows a more efficient way to poll as that can first give you a list of movements that have new messages and then use this endpoint to retrieve the updated messages for those movements.
          required: false
          schema:
            $ref: "#/components/schemas/DateTime"
      responses:
        '200':
          description: Successful operation
          content:
            application/vnd.hmrc.1.0+json:
              example:
                - encodedMessage: PElFODE1PjwhLS0gRXhhbXBsZSBJRTgxNSBtZXNzYWdlIC0tPjwvSUU4MTU+
                  createdOn: 2023-10-30T15:36:08.985Z
                  type: IE815
                - encodedMessage: PElFODAxPjwhLS0gRXhhbXBsZSBJRTgwMSBtZXNzYWdlIC0tPjwvSUU4MDE+
                  createdOn: 2023-10-28T15:36:08.985Z
                  type: IE801
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MessageWithType'
        '401':
          description: Consignor or Consignee not authorized. Invalid enrolment parameter.
        '403':
          description: The requested movement's consignor ID or consignee ID is not in authorisation bearer token
        '404':
          description: Unknown movement, based on the provided local reference number
      security:
        - userRestricted:
            - excise-movement-control-system
  
  /customs/excise/traders/pre-validate:
    post:
      tags:
        - Traders
      summary: Get information relating to an excise trader
      description: Get information relating to an excise trader.
      operationId: prevalidateTrader
      parameters:
        - $ref: "#/components/parameters/AcceptHeader"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PreValidateTraderRequest'
            examples:
              Successful Validation Request:
                summary: Pre Validate Trader Request
                value:
                  exciseTraderValidationRequest:
                    exciseTraderRequest:
                      exciseRegistrationNumber: GBWK002281023
                      entityGroup: UK Record
                      validateProductAuthorisationRequest:
                        - product:
                            exciseProductCode: W200


      responses:
        '200':
          description: validation performed - either successfully or with a business error (invalid trader, invalid product codes)
          content:
            application/vnd.hmrc.1.0+json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/ExciseTraderValidationSuccessfulResponse'
                  - $ref: '#/components/schemas/ExciseTraderValidationErrorResponse'
              examples:
                Success:
                  summary: "Validated successfully"
                  value:
                    exciseTraderValidationResponse:
                      validationTimestamp: '2001-12-17T09:30:47-05:00'
                      exciseTraderResponse:
                        - exciseRegistrationNumber: GBWK002281023
                          entityGroup: UK Record
                          validTrader: true
                          traderType: '1'
                          validateProductAuthorisationResponse:
                            valid: true

                Invalid trader:
                  summary: "Invalid trader"
                  value:
                    validationTimeStamp: '2001-12-17T09:30:47-05:00'
                    exciseTraderResponse:
                      - exciseRegistrationNumber: GBWK000000200
                        entityGroup: UK Record
                        validTrader: false
                        errorCode: '6'
                        errorText: Not Found
                Invalid product codes:
                  summary: Invalid product codes
                  value:
                    validationTimeStamp: '2001-12-17T09:30:47-05:00'
                    exciseTraderResponse:
                      - exciseRegistrationNumber: GBWK000000206
                        entityGroup: UK Record
                        validTrader: true
                        traderType: '1'
                        validateProductAuthorisationResponse:
                          valid: false
                          productError:
                            - exciseProductCode: W300
                              errorCode: '2'
                              errorText: Unauthorised EPC
                            - exciseProductCode: S200
                              errorCode: '1'
                              errorText: Unrecognised EPC
        '400':
          description: Invalid JSON or mandatory fields missing.
        '500':
          description: Internal server error
      security:
        - userRestricted:
            - excise-movement-control-system
components:
  parameters:
    AcceptHeader:
      name: Accept
      in: header
      description: >-
        Specifies the response format and the
        [version](/api-documentation/docs/reference-guide#versioning) of the API
        to be used.
      required: true
      schema:
        type: string
        enum: [
          "application/vnd.hmrc.1.0+json"
        ]
    ContentTypeHeader:
      name: Content-Type
      in: header
      description: The media type of the request body.
      schema:
        type: string
        enum:
          - application/xml
      required: true
  schemas:
    AdministrativeReferenceCode:
      type: string
      pattern: '[0-9]{2}[A-Z]{2}[A-Z0-9]{16}[0-9]'
    LocalReferenceNumber:
      type: string
      pattern: '.{1,22}'
    ConsigneeId:
      type: string
      pattern: '.{1,16}'
    ExciseReferenceNumber:
      type: string
      pattern: '[A-Z]{2}[a-zA-Z0-9]{11}'
    MovementStatus:
      type: string
      enum:
        - Accepted
        - Accepted for export
        - Cancelled
        - Delivered
        - Diverted
        - e-AD/e-SAD manually closed
        - Exporting
        - None
        - Partially refused
        - Refused
        - Rejected
        - Replaced
        - Stopped
    DateTime:
      type: string
      format: date-time
      example: '2021-12-17T09:30:47Z'
    CorrelationId:
      type: string
      format: uuid
      example: 3e8dae97-b586-4cef-8511-68ac12da9028
    IE810:
      type: object
      description: Submit cancellation
      xml:
        name: IE810
    IE813:
      type: object
      description: Submit change of destination
      xml:
        name: IE813
    IE815:
      type: object
      description: Submit draft movement
      xml:
        name: IE815
    IE818:
      type: object
      description: Submit report of receipt
      xml:
        name: IE818
    IE819:
      type: object
      description: Submit alert or rejection
      xml:
        name: IE819
    IE825:
      type: object
      description: Submit split movement
      xml:
        name: IE825
    IE837:
      type: object
      description: Submit explanation for delay
      xml:
        name: IE837
    IE871:
      type: object
      description: Submit reason for shortage
      xml:
        name: IE871
    TraderType:
      type: string
      enum: [ 1,2,3,4,5,6,7 ]
      description: 1 = Warehouse Keeper<br />
        2 = Tax Warehouse<br />
        3 = Registered Consignor<br />
        4 = Registered Consignee<br />
        5 = Temporary Registered Consignee<br />
        6 = Temporary Registered Authorisation<br />
        7 = Other
    ExciseProductCode:
      type: string
      description: The excise product category code
      maxLength: 4
      pattern: '[A-Z][0-9]{3}'
      example: 'W200'
    ProductRequest:
      type: object
      required:
        - exciseProductCode
      properties:
        exciseProductCode:
          $ref: '#/components/schemas/ExciseProductCode'
    ExciseMovement:
      type: object
      required:
        - consignorId
        - localReferenceNumber
        - status
      properties:
        consignorId:
          $ref: '#/components/schemas/ExciseReferenceNumber'
        localReferenceNumber:
          $ref: '#/components/schemas/LocalReferenceNumber'
        consigneeId:
          $ref: '#/components/schemas/ConsigneeId'
        administrativeReferenceCode:
          $ref: '#/components/schemas/AdministrativeReferenceCode'
        status:
          $ref: '#/components/schemas/MovementStatus'
      xml:
        name: exciseMovement
    ExciseMovementError:
      type: object
      required:
        - dateTime
        - message
        - debugMessage
        - emcsCorrelationId
      properties:
        dateTime:
          $ref: '#/components/schemas/DateTime'
        emcsCorrelationId:
          $ref: '#/components/schemas/CorrelationId'
        message:
          type: string
        debugMessage:
          type: string
        errors:
          type: array
          items:
            $ref: '#/components/schemas/ValidationError'
      xml:
        name: exciseMovementType
    ValidationError:
      type: object
      required:
        - errorCode
        - errorMessage
        - location
        - value
      properties:
        errorCode:
          type: integer
        errorMessage:
          type: string
        location:
          type: string
        value:
          type: string
    SubmitDraftMessageType:
      type: string
      description: The submit draft message type
      enum:
        - IE815
      xml:
        name: type
    IncomingMessageType:
      type: string
      description: The type of incoming message
      enum:
        - IE810
        - IE813
        - IE818
        - IE819
        #        Temporarily commented out until MVP+
        #        - IE825
        - IE837
        - IE871
      xml:
        name: type
    OutgoingMessageType:
      type: string
      description: The type of outgoing message
      enum:
        - IE704
        - IE801
        - IE802
        - IE803
        - IE807
        - IE829
        - IE839
        - IE840
        - IE881
        - IE905
      xml:
        name: type
    MessageType:
      allOf:
        - $ref: '#/components/schemas/SubmitDraftMessageType'
        - $ref: '#/components/schemas/IncomingMessageType'
        - $ref: '#/components/schemas/OutgoingMessageType'
    Message:
      required:
        - encodedMessage
        - createdOn
      type: object
      properties:
        encodedMessage:
          type: string
          format: byte
        createdOn:
          $ref: "#/components/schemas/DateTime"
      xml:
        name: message
    MessageWithType:
      allOf:
        - $ref: '#/components/schemas/Message'
        - type: object
          required:
            - type
          properties:
            type:
              $ref: '#/components/schemas/MessageType'
    PreValidateTraderRequest:
      required:
        - exciseTraderValidationRequest
      properties:
        exciseTraderValidationRequest:
          $ref: '#/components/schemas/ExciseTraderValidationRequest'
    ExciseTraderValidationRequest:
      required:
        - exciseTraderRequest
      type: object
      properties:
        exciseTraderRequest:
          $ref: '#/components/schemas/ExciseTraderRequest'
    ExciseTraderRequest:
      required:
        - exciseRegistrationNumber
        - entityGroup
        - validateProductAuthorisationRequest
      type: object
      properties:
        exciseRegistrationNumber:
          $ref: '#/components/schemas/ExciseReferenceNumber'
        entityGroup:
          $ref: '#/components/schemas/EntityGroup'
        validateProductAuthorisationRequest:
          $ref: '#/components/schemas/ValidateProductAuthorisationRequest'
    EntityGroup:
      type: string
      enum: [ 'UK Record', 'EU Trader', 'EU Warehouse', 'EU Temporary Authorisation' ]
      example: 'UK Record'
    ValidateProductAuthorisationRequest:
      type: object
      required:
        - product
      properties:
        product:
          $ref: '#/components/schemas/ProductRequest'
    ExciseTraderValidationSuccessfulResponse:
      type: object
      required:
        - exciseTraderValidationResponse
      properties:
        exciseTraderValidationResponse:
          $ref: '#/components/schemas/ExciseTraderValidationResponse'
    ExciseTraderValidationResponse:
      type: object
      required:
        - validationTimestamp
        - exciseTraderResponse
      properties:
        validationTimestamp:
          $ref: '#/components/schemas/ValidationTimestamp'
        exciseTraderResponse:
          type: array
          items:
            $ref: '#/components/schemas/ExciseTraderResponse'
    ExciseTraderResponse:
      type: object
      required:
        - exciseRegistrationNumber
        - entityGroup
        - validTrader
        - validateProductAuthorisationResponse
      properties:
        exciseRegistrationNumber:
          $ref: '#/components/schemas/ExciseReferenceNumber'
        entityGroup:
          $ref: '#/components/schemas/EntityGroup'
        validTrader:
          type: boolean
        traderType:
          $ref: '#/components/schemas/TraderType'
        validateProductAuthorisationResponse:
          $ref: '#/components/schemas/ValidateProductAuthorisationResponse'
    ValidateProductAuthorisationResponse:
      type: object
      required:
        - valid
      properties:
        valid:
          type: boolean
    ValidationTimestamp:
      type: string
      example: '2001-12-17T09:30:47-05:00'
      pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}(\\.[0-9]+)?([+-][0-9]{2}:[0-9]{2})?$'
    ExciseTraderValidationErrorResponse:
      type: object
      required:
        - validationTimestamp
        - exciseTraderResponse
      properties:
        validationTimestamp:
          $ref: '#/components/schemas/ValidationTimestamp'
        exciseTraderValidationResponse:
          type: array
          items:
            $ref: '#/components/schemas/ExciseTraderErrorResponse'
    ExciseTraderErrorResponse:
      type: object
      required:
        - exciseRegistrationNumber
        - entityGroup
        - validTrader
      properties:
        exciseRegistrationNumber:
          $ref: '#/components/schemas/ExciseReferenceNumber'
        entityGroup:
          $ref: '#/components/schemas/EntityGroup'
        validTrader:
          type: boolean
        errorCode:
          type: string
          enum: [ "1", "2", "3", "4", "5", "6" ]
          description: The 'errorCode' for an invalid trader i.e., when validTrader = "false".<br /> 1 = Pending<br /> 2 = Expired<br /> 3 = Withdrawn<br /> 4 = Cancelled<br /> 5 = Used<br /> 6 = Not Found
        errorText:
          type: string
        traderType:
          $ref: '#/components/schemas/TraderType'
        validateProductAuthorisationResponse:
          $ref: '#/components/schemas/ValidateProductAuthorisationErrorResponse'
    ValidateProductAuthorisationErrorResponse:
      type: object
      required:
        - valid
      properties:
        valid:
          type: boolean
        productError:
          type: array
          items:
            $ref: '#/components/schemas/ProductError'
    ProductError:
      type: object
      required:
        - exciseProductCode
        - errorCode
        - errorText
      properties:
        exciseProductCode:
          $ref: '#/components/schemas/ExciseProductCode'
        errorCode:
          type: string
          enum: [ "1", "2", "3" ]
          description: 1 = Unrecognised EPC<br /> 2 = Unauthorised EPC<br /> 3 = EPC exceeded
        errorText:
          type: string
          description: "The 'errorText' will be populated with:<br /> 'Unrecognised EPC' if errorCode = 1<br />'Unauthorised EPC' if errorCode = 2<br />'EPC exceeded' if errorCode = 3"
  securitySchemes:
    userRestricted:
      type: oauth2
      description: HMRC supports OAuth 2.0 for authenticating user restricted API
        requests using an OAuth 2.0 Bearer Token in the AUTHORIZATION header. See
        https://developer.service.hmrc.gov.uk/api-documentation/docs/authorisation/user-restricted-endpoints
        for details.
      flows:
        authorizationCode:
          authorizationUrl: https://api.service.hmrc.gov.uk/oauth/authorize
          tokenUrl: https://api.service.hmrc.gov.uk/oauth/token
          refreshUrl: https://api.service.hmrc.gov.uk/oauth/refresh
          scopes:
            excise-movement-control-system: Access all aspects of EMCS API
    applicationRestricted:
      type: oauth2
      description: HMRC supports OAuth 2.0 for authenticating application restricted
        API  requests using an OAuth 2.0 Bearer Token in the AUTHORIZATION header.
        See https://developer.service.hmrc.gov.uk/api-documentation/docs/authorisation/application-restricted-endpoints
        for details.
      flows:
        clientCredentials:
          tokenUrl: https://api.service.hmrc.gov.uk/oauth/token
          scopes:
            excise-movement-control-system: Access push-pull-notification box information
              via the EMCS API

